// Copyright (C) 2004 Arkadiy Vertleyb
// Copyright (C) 2004 Peder Holt
// Use, modification and distribution is subject to the Boost Software
// License, Version 1.0. (http://www.boost.org/LICENSE_1_0.txt)

#ifndef AUTOBOOST_TYPEOF_REGISTER_FUNDAMENTAL_HPP_INCLUDED
#define AUTOBOOST_TYPEOF_REGISTER_FUNDAMENTAL_HPP_INCLUDED

#include <autoboost/typeof/typeof.hpp>

#include AUTOBOOST_TYPEOF_INCREMENT_REGISTRATION_GROUP()

AUTOBOOST_TYPEOF_REGISTER_TYPE(unsigned char)
AUTOBOOST_TYPEOF_REGISTER_TYPE(unsigned short)
AUTOBOOST_TYPEOF_REGISTER_TYPE(unsigned int)
AUTOBOOST_TYPEOF_REGISTER_TYPE(unsigned long)

AUTOBOOST_TYPEOF_REGISTER_TYPE(signed char)
AUTOBOOST_TYPEOF_REGISTER_TYPE(signed short)
AUTOBOOST_TYPEOF_REGISTER_TYPE(signed int)
AUTOBOOST_TYPEOF_REGISTER_TYPE(signed long)

AUTOBOOST_TYPEOF_REGISTER_TYPE(bool)
AUTOBOOST_TYPEOF_REGISTER_TYPE(char)

AUTOBOOST_TYPEOF_REGISTER_TYPE(float)
AUTOBOOST_TYPEOF_REGISTER_TYPE(double)
AUTOBOOST_TYPEOF_REGISTER_TYPE(long double)

#ifndef AUTOBOOST_NO_INTRINSIC_WCHAR_T
// If the following line fails to compile and you're using the Intel
// compiler, see http://lists.boost.org/MailArchives/autoboost-users/msg06567.php,
// and define AUTOBOOST_NO_INTRINSIC_WCHAR_T on the command line.
AUTOBOOST_TYPEOF_REGISTER_TYPE(wchar_t)
#endif

#if (defined(AUTOBOOST_MSVC) && (AUTOBOOST_MSVC == 1200)) \
    || (defined(AUTOBOOST_INTEL_CXX_VERSION) && defined(_MSC_VER) && (AUTOBOOST_INTEL_CXX_VERSION <= 600)) \
    || (defined(__BORLANDC__) && (__BORLANDC__ == 0x600) && (_MSC_VER == 1200))
AUTOBOOST_TYPEOF_REGISTER_TYPE(unsigned __int8)
AUTOBOOST_TYPEOF_REGISTER_TYPE(__int8)
AUTOBOOST_TYPEOF_REGISTER_TYPE(unsigned __int16)
AUTOBOOST_TYPEOF_REGISTER_TYPE(__int16)
AUTOBOOST_TYPEOF_REGISTER_TYPE(unsigned __int32)
AUTOBOOST_TYPEOF_REGISTER_TYPE(__int32)
#ifdef __BORLANDC__
AUTOBOOST_TYPEOF_REGISTER_TYPE(unsigned __int64)
AUTOBOOST_TYPEOF_REGISTER_TYPE(__int64)
#endif
#endif

# if defined(AUTOBOOST_HAS_LONG_LONG)
AUTOBOOST_TYPEOF_REGISTER_TYPE(::autoboost::ulong_long_type)
AUTOBOOST_TYPEOF_REGISTER_TYPE(::autoboost::long_long_type)
#elif defined(AUTOBOOST_HAS_MS_INT64)
AUTOBOOST_TYPEOF_REGISTER_TYPE(unsigned __int64)
AUTOBOOST_TYPEOF_REGISTER_TYPE(__int64)
#endif

AUTOBOOST_TYPEOF_REGISTER_TYPE(void)

#endif//AUTOBOOST_TYPEOF_REGISTER_FUNDAMENTAL_HPP_INCLUDED
