
// NO INCLUDE GUARDS, THE HEADER IS INTENDED FOR MULTIPLE INCLUSION

// Copyright Aleksey Gurtovoy 2002-2004
//
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

// $Source$
// $Date$
// $Revision$

#undef AUTOBOOST_TT_AUX_BOOL_TRAIT_VALUE_DECL
#undef AUTOBOOST_TT_AUX_BOOL_C_BASE
#undef AUTOBOOST_TT_AUX_BOOL_TRAIT_DEF1
#undef AUTOBOOST_TT_AUX_BOOL_TRAIT_DEF2
#undef AUTOBOOST_TT_AUX_BOOL_TRAIT_DEF3
#undef AUTOBOOST_TT_AUX_BOOL_TRAIT_SPEC1
#undef AUTOBOOST_TT_AUX_BOOL_TRAIT_SPEC2
#undef AUTOBOOST_TT_AUX_BOOL_TRAIT_IMPL_SPEC1
#undef AUTOBOOST_TT_AUX_BOOL_TRAIT_IMPL_SPEC2
#undef AUTOBOOST_TT_AUX_BOOL_TRAIT_PARTIAL_SPEC1_1
#undef AUTOBOOST_TT_AUX_BOOL_TRAIT_PARTIAL_SPEC1_2
#undef AUTOBOOST_TT_AUX_BOOL_TRAIT_PARTIAL_SPEC2_1
#undef AUTOBOOST_TT_AUX_BOOL_TRAIT_PARTIAL_SPEC2_2
#undef AUTOBOOST_TT_AUX_BOOL_TRAIT_IMPL_PARTIAL_SPEC2_1
#undef AUTOBOOST_TT_AUX_BOOL_TRAIT_CV_SPEC1
