# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.
#  *     Distributed under the Boost Software License, Version 1.0. (See
#  *     accompanying file LICENSE_1_0.txt or copy at
#  *     http://www.boost.org/LICENSE_1_0.txt)
#  *                                                                          *
#  ************************************************************************** */
#
# /* See http://www.boost.org for most recent version. */
#
# ifndef AUTOBOOST_PREPROCESSOR_DETAIL_AUTO_REC_HPP
# define AUTOBOOST_PREPROCESSOR_DETAIL_AUTO_REC_HPP
#
# include <autoboost/preprocessor/control/iif.hpp>
#
# /* AUTOBOOST_PP_AUTO_REC */
#
# define AUTOBOOST_PP_AUTO_REC(pred, n) AUTOBOOST_PP_NODE_ENTRY_ ## n(pred)
#
# define AUTOBOOST_PP_NODE_ENTRY_256(p) AUTOBOOST_PP_NODE_128(p)(p)(p)(p)(p)(p)(p)(p)
# define AUTOBOOST_PP_NODE_ENTRY_128(p) AUTOBOOST_PP_NODE_64(p)(p)(p)(p)(p)(p)(p)
# define AUTOBOOST_PP_NODE_ENTRY_64(p) AUTOBOOST_PP_NODE_32(p)(p)(p)(p)(p)(p)
# define AUTOBOOST_PP_NODE_ENTRY_32(p) AUTOBOOST_PP_NODE_16(p)(p)(p)(p)(p)
# define AUTOBOOST_PP_NODE_ENTRY_16(p) AUTOBOOST_PP_NODE_8(p)(p)(p)(p)
# define AUTOBOOST_PP_NODE_ENTRY_8(p) AUTOBOOST_PP_NODE_4(p)(p)(p)
# define AUTOBOOST_PP_NODE_ENTRY_4(p) AUTOBOOST_PP_NODE_2(p)(p)
# define AUTOBOOST_PP_NODE_ENTRY_2(p) AUTOBOOST_PP_NODE_1(p)
#
# define AUTOBOOST_PP_NODE_128(p) AUTOBOOST_PP_IIF(p##(128), AUTOBOOST_PP_NODE_64, AUTOBOOST_PP_NODE_192)
#    define AUTOBOOST_PP_NODE_64(p) AUTOBOOST_PP_IIF(p##(64), AUTOBOOST_PP_NODE_32, AUTOBOOST_PP_NODE_96)
#        define AUTOBOOST_PP_NODE_32(p) AUTOBOOST_PP_IIF(p##(32), AUTOBOOST_PP_NODE_16, AUTOBOOST_PP_NODE_48)
#            define AUTOBOOST_PP_NODE_16(p) AUTOBOOST_PP_IIF(p##(16), AUTOBOOST_PP_NODE_8, AUTOBOOST_PP_NODE_24)
#                define AUTOBOOST_PP_NODE_8(p) AUTOBOOST_PP_IIF(p##(8), AUTOBOOST_PP_NODE_4, AUTOBOOST_PP_NODE_12)
#                    define AUTOBOOST_PP_NODE_4(p) AUTOBOOST_PP_IIF(p##(4), AUTOBOOST_PP_NODE_2, AUTOBOOST_PP_NODE_6)
#                        define AUTOBOOST_PP_NODE_2(p) AUTOBOOST_PP_IIF(p##(2), AUTOBOOST_PP_NODE_1, AUTOBOOST_PP_NODE_3)
#                            define AUTOBOOST_PP_NODE_1(p) AUTOBOOST_PP_IIF(p##(1), 1, 2)
#                            define AUTOBOOST_PP_NODE_3(p) AUTOBOOST_PP_IIF(p##(3), 3, 4)
#                        define AUTOBOOST_PP_NODE_6(p) AUTOBOOST_PP_IIF(p##(6), AUTOBOOST_PP_NODE_5, AUTOBOOST_PP_NODE_7)
#                            define AUTOBOOST_PP_NODE_5(p) AUTOBOOST_PP_IIF(p##(5), 5, 6)
#                            define AUTOBOOST_PP_NODE_7(p) AUTOBOOST_PP_IIF(p##(7), 7, 8)
#                    define AUTOBOOST_PP_NODE_12(p) AUTOBOOST_PP_IIF(p##(12), AUTOBOOST_PP_NODE_10, AUTOBOOST_PP_NODE_14)
#                        define AUTOBOOST_PP_NODE_10(p) AUTOBOOST_PP_IIF(p##(10), AUTOBOOST_PP_NODE_9, AUTOBOOST_PP_NODE_11)
#                            define AUTOBOOST_PP_NODE_9(p) AUTOBOOST_PP_IIF(p##(9), 9, 10)
#                            define AUTOBOOST_PP_NODE_11(p) AUTOBOOST_PP_IIF(p##(11), 11, 12)
#                        define AUTOBOOST_PP_NODE_14(p) AUTOBOOST_PP_IIF(p##(14), AUTOBOOST_PP_NODE_13, AUTOBOOST_PP_NODE_15)
#                            define AUTOBOOST_PP_NODE_13(p) AUTOBOOST_PP_IIF(p##(13), 13, 14)
#                            define AUTOBOOST_PP_NODE_15(p) AUTOBOOST_PP_IIF(p##(15), 15, 16)
#                define AUTOBOOST_PP_NODE_24(p) AUTOBOOST_PP_IIF(p##(24), AUTOBOOST_PP_NODE_20, AUTOBOOST_PP_NODE_28)
#                    define AUTOBOOST_PP_NODE_20(p) AUTOBOOST_PP_IIF(p##(20), AUTOBOOST_PP_NODE_18, AUTOBOOST_PP_NODE_22)
#                        define AUTOBOOST_PP_NODE_18(p) AUTOBOOST_PP_IIF(p##(18), AUTOBOOST_PP_NODE_17, AUTOBOOST_PP_NODE_19)
#                            define AUTOBOOST_PP_NODE_17(p) AUTOBOOST_PP_IIF(p##(17), 17, 18)
#                            define AUTOBOOST_PP_NODE_19(p) AUTOBOOST_PP_IIF(p##(19), 19, 20)
#                        define AUTOBOOST_PP_NODE_22(p) AUTOBOOST_PP_IIF(p##(22), AUTOBOOST_PP_NODE_21, AUTOBOOST_PP_NODE_23)
#                            define AUTOBOOST_PP_NODE_21(p) AUTOBOOST_PP_IIF(p##(21), 21, 22)
#                            define AUTOBOOST_PP_NODE_23(p) AUTOBOOST_PP_IIF(p##(23), 23, 24)
#                    define AUTOBOOST_PP_NODE_28(p) AUTOBOOST_PP_IIF(p##(28), AUTOBOOST_PP_NODE_26, AUTOBOOST_PP_NODE_30)
#                        define AUTOBOOST_PP_NODE_26(p) AUTOBOOST_PP_IIF(p##(26), AUTOBOOST_PP_NODE_25, AUTOBOOST_PP_NODE_27)
#                            define AUTOBOOST_PP_NODE_25(p) AUTOBOOST_PP_IIF(p##(25), 25, 26)
#                            define AUTOBOOST_PP_NODE_27(p) AUTOBOOST_PP_IIF(p##(27), 27, 28)
#                        define AUTOBOOST_PP_NODE_30(p) AUTOBOOST_PP_IIF(p##(30), AUTOBOOST_PP_NODE_29, AUTOBOOST_PP_NODE_31)
#                            define AUTOBOOST_PP_NODE_29(p) AUTOBOOST_PP_IIF(p##(29), 29, 30)
#                            define AUTOBOOST_PP_NODE_31(p) AUTOBOOST_PP_IIF(p##(31), 31, 32)
#            define AUTOBOOST_PP_NODE_48(p) AUTOBOOST_PP_IIF(p##(48), AUTOBOOST_PP_NODE_40, AUTOBOOST_PP_NODE_56)
#                define AUTOBOOST_PP_NODE_40(p) AUTOBOOST_PP_IIF(p##(40), AUTOBOOST_PP_NODE_36, AUTOBOOST_PP_NODE_44)
#                    define AUTOBOOST_PP_NODE_36(p) AUTOBOOST_PP_IIF(p##(36), AUTOBOOST_PP_NODE_34, AUTOBOOST_PP_NODE_38)
#                        define AUTOBOOST_PP_NODE_34(p) AUTOBOOST_PP_IIF(p##(34), AUTOBOOST_PP_NODE_33, AUTOBOOST_PP_NODE_35)
#                            define AUTOBOOST_PP_NODE_33(p) AUTOBOOST_PP_IIF(p##(33), 33, 34)
#                            define AUTOBOOST_PP_NODE_35(p) AUTOBOOST_PP_IIF(p##(35), 35, 36)
#                        define AUTOBOOST_PP_NODE_38(p) AUTOBOOST_PP_IIF(p##(38), AUTOBOOST_PP_NODE_37, AUTOBOOST_PP_NODE_39)
#                            define AUTOBOOST_PP_NODE_37(p) AUTOBOOST_PP_IIF(p##(37), 37, 38)
#                            define AUTOBOOST_PP_NODE_39(p) AUTOBOOST_PP_IIF(p##(39), 39, 40)
#                    define AUTOBOOST_PP_NODE_44(p) AUTOBOOST_PP_IIF(p##(44), AUTOBOOST_PP_NODE_42, AUTOBOOST_PP_NODE_46)
#                        define AUTOBOOST_PP_NODE_42(p) AUTOBOOST_PP_IIF(p##(42), AUTOBOOST_PP_NODE_41, AUTOBOOST_PP_NODE_43)
#                            define AUTOBOOST_PP_NODE_41(p) AUTOBOOST_PP_IIF(p##(41), 41, 42)
#                            define AUTOBOOST_PP_NODE_43(p) AUTOBOOST_PP_IIF(p##(43), 43, 44)
#                        define AUTOBOOST_PP_NODE_46(p) AUTOBOOST_PP_IIF(p##(46), AUTOBOOST_PP_NODE_45, AUTOBOOST_PP_NODE_47)
#                            define AUTOBOOST_PP_NODE_45(p) AUTOBOOST_PP_IIF(p##(45), 45, 46)
#                            define AUTOBOOST_PP_NODE_47(p) AUTOBOOST_PP_IIF(p##(47), 47, 48)
#                define AUTOBOOST_PP_NODE_56(p) AUTOBOOST_PP_IIF(p##(56), AUTOBOOST_PP_NODE_52, AUTOBOOST_PP_NODE_60)
#                    define AUTOBOOST_PP_NODE_52(p) AUTOBOOST_PP_IIF(p##(52), AUTOBOOST_PP_NODE_50, AUTOBOOST_PP_NODE_54)
#                        define AUTOBOOST_PP_NODE_50(p) AUTOBOOST_PP_IIF(p##(50), AUTOBOOST_PP_NODE_49, AUTOBOOST_PP_NODE_51)
#                            define AUTOBOOST_PP_NODE_49(p) AUTOBOOST_PP_IIF(p##(49), 49, 50)
#                            define AUTOBOOST_PP_NODE_51(p) AUTOBOOST_PP_IIF(p##(51), 51, 52)
#                        define AUTOBOOST_PP_NODE_54(p) AUTOBOOST_PP_IIF(p##(54), AUTOBOOST_PP_NODE_53, AUTOBOOST_PP_NODE_55)
#                            define AUTOBOOST_PP_NODE_53(p) AUTOBOOST_PP_IIF(p##(53), 53, 54)
#                            define AUTOBOOST_PP_NODE_55(p) AUTOBOOST_PP_IIF(p##(55), 55, 56)
#                    define AUTOBOOST_PP_NODE_60(p) AUTOBOOST_PP_IIF(p##(60), AUTOBOOST_PP_NODE_58, AUTOBOOST_PP_NODE_62)
#                        define AUTOBOOST_PP_NODE_58(p) AUTOBOOST_PP_IIF(p##(58), AUTOBOOST_PP_NODE_57, AUTOBOOST_PP_NODE_59)
#                            define AUTOBOOST_PP_NODE_57(p) AUTOBOOST_PP_IIF(p##(57), 57, 58)
#                            define AUTOBOOST_PP_NODE_59(p) AUTOBOOST_PP_IIF(p##(59), 59, 60)
#                        define AUTOBOOST_PP_NODE_62(p) AUTOBOOST_PP_IIF(p##(62), AUTOBOOST_PP_NODE_61, AUTOBOOST_PP_NODE_63)
#                            define AUTOBOOST_PP_NODE_61(p) AUTOBOOST_PP_IIF(p##(61), 61, 62)
#                            define AUTOBOOST_PP_NODE_63(p) AUTOBOOST_PP_IIF(p##(63), 63, 64)
#        define AUTOBOOST_PP_NODE_96(p) AUTOBOOST_PP_IIF(p##(96), AUTOBOOST_PP_NODE_80, AUTOBOOST_PP_NODE_112)
#            define AUTOBOOST_PP_NODE_80(p) AUTOBOOST_PP_IIF(p##(80), AUTOBOOST_PP_NODE_72, AUTOBOOST_PP_NODE_88)
#                define AUTOBOOST_PP_NODE_72(p) AUTOBOOST_PP_IIF(p##(72), AUTOBOOST_PP_NODE_68, AUTOBOOST_PP_NODE_76)
#                    define AUTOBOOST_PP_NODE_68(p) AUTOBOOST_PP_IIF(p##(68), AUTOBOOST_PP_NODE_66, AUTOBOOST_PP_NODE_70)
#                        define AUTOBOOST_PP_NODE_66(p) AUTOBOOST_PP_IIF(p##(66), AUTOBOOST_PP_NODE_65, AUTOBOOST_PP_NODE_67)
#                            define AUTOBOOST_PP_NODE_65(p) AUTOBOOST_PP_IIF(p##(65), 65, 66)
#                            define AUTOBOOST_PP_NODE_67(p) AUTOBOOST_PP_IIF(p##(67), 67, 68)
#                        define AUTOBOOST_PP_NODE_70(p) AUTOBOOST_PP_IIF(p##(70), AUTOBOOST_PP_NODE_69, AUTOBOOST_PP_NODE_71)
#                            define AUTOBOOST_PP_NODE_69(p) AUTOBOOST_PP_IIF(p##(69), 69, 70)
#                            define AUTOBOOST_PP_NODE_71(p) AUTOBOOST_PP_IIF(p##(71), 71, 72)
#                    define AUTOBOOST_PP_NODE_76(p) AUTOBOOST_PP_IIF(p##(76), AUTOBOOST_PP_NODE_74, AUTOBOOST_PP_NODE_78)
#                        define AUTOBOOST_PP_NODE_74(p) AUTOBOOST_PP_IIF(p##(74), AUTOBOOST_PP_NODE_73, AUTOBOOST_PP_NODE_75)
#                            define AUTOBOOST_PP_NODE_73(p) AUTOBOOST_PP_IIF(p##(73), 73, 74)
#                            define AUTOBOOST_PP_NODE_75(p) AUTOBOOST_PP_IIF(p##(75), 75, 76)
#                        define AUTOBOOST_PP_NODE_78(p) AUTOBOOST_PP_IIF(p##(78), AUTOBOOST_PP_NODE_77, AUTOBOOST_PP_NODE_79)
#                            define AUTOBOOST_PP_NODE_77(p) AUTOBOOST_PP_IIF(p##(77), 77, 78)
#                            define AUTOBOOST_PP_NODE_79(p) AUTOBOOST_PP_IIF(p##(79), 79, 80)
#                define AUTOBOOST_PP_NODE_88(p) AUTOBOOST_PP_IIF(p##(88), AUTOBOOST_PP_NODE_84, AUTOBOOST_PP_NODE_92)
#                    define AUTOBOOST_PP_NODE_84(p) AUTOBOOST_PP_IIF(p##(84), AUTOBOOST_PP_NODE_82, AUTOBOOST_PP_NODE_86)
#                        define AUTOBOOST_PP_NODE_82(p) AUTOBOOST_PP_IIF(p##(82), AUTOBOOST_PP_NODE_81, AUTOBOOST_PP_NODE_83)
#                            define AUTOBOOST_PP_NODE_81(p) AUTOBOOST_PP_IIF(p##(81), 81, 82)
#                            define AUTOBOOST_PP_NODE_83(p) AUTOBOOST_PP_IIF(p##(83), 83, 84)
#                        define AUTOBOOST_PP_NODE_86(p) AUTOBOOST_PP_IIF(p##(86), AUTOBOOST_PP_NODE_85, AUTOBOOST_PP_NODE_87)
#                            define AUTOBOOST_PP_NODE_85(p) AUTOBOOST_PP_IIF(p##(85), 85, 86)
#                            define AUTOBOOST_PP_NODE_87(p) AUTOBOOST_PP_IIF(p##(87), 87, 88)
#                    define AUTOBOOST_PP_NODE_92(p) AUTOBOOST_PP_IIF(p##(92), AUTOBOOST_PP_NODE_90, AUTOBOOST_PP_NODE_94)
#                        define AUTOBOOST_PP_NODE_90(p) AUTOBOOST_PP_IIF(p##(90), AUTOBOOST_PP_NODE_89, AUTOBOOST_PP_NODE_91)
#                            define AUTOBOOST_PP_NODE_89(p) AUTOBOOST_PP_IIF(p##(89), 89, 90)
#                            define AUTOBOOST_PP_NODE_91(p) AUTOBOOST_PP_IIF(p##(91), 91, 92)
#                        define AUTOBOOST_PP_NODE_94(p) AUTOBOOST_PP_IIF(p##(94), AUTOBOOST_PP_NODE_93, AUTOBOOST_PP_NODE_95)
#                            define AUTOBOOST_PP_NODE_93(p) AUTOBOOST_PP_IIF(p##(93), 93, 94)
#                            define AUTOBOOST_PP_NODE_95(p) AUTOBOOST_PP_IIF(p##(95), 95, 96)
#            define AUTOBOOST_PP_NODE_112(p) AUTOBOOST_PP_IIF(p##(112), AUTOBOOST_PP_NODE_104, AUTOBOOST_PP_NODE_120)
#                define AUTOBOOST_PP_NODE_104(p) AUTOBOOST_PP_IIF(p##(104), AUTOBOOST_PP_NODE_100, AUTOBOOST_PP_NODE_108)
#                    define AUTOBOOST_PP_NODE_100(p) AUTOBOOST_PP_IIF(p##(100), AUTOBOOST_PP_NODE_98, AUTOBOOST_PP_NODE_102)
#                        define AUTOBOOST_PP_NODE_98(p) AUTOBOOST_PP_IIF(p##(98), AUTOBOOST_PP_NODE_97, AUTOBOOST_PP_NODE_99)
#                            define AUTOBOOST_PP_NODE_97(p) AUTOBOOST_PP_IIF(p##(97), 97, 98)
#                            define AUTOBOOST_PP_NODE_99(p) AUTOBOOST_PP_IIF(p##(99), 99, 100)
#                        define AUTOBOOST_PP_NODE_102(p) AUTOBOOST_PP_IIF(p##(102), AUTOBOOST_PP_NODE_101, AUTOBOOST_PP_NODE_103)
#                            define AUTOBOOST_PP_NODE_101(p) AUTOBOOST_PP_IIF(p##(101), 101, 102)
#                            define AUTOBOOST_PP_NODE_103(p) AUTOBOOST_PP_IIF(p##(103), 103, 104)
#                    define AUTOBOOST_PP_NODE_108(p) AUTOBOOST_PP_IIF(p##(108), AUTOBOOST_PP_NODE_106, AUTOBOOST_PP_NODE_110)
#                        define AUTOBOOST_PP_NODE_106(p) AUTOBOOST_PP_IIF(p##(106), AUTOBOOST_PP_NODE_105, AUTOBOOST_PP_NODE_107)
#                            define AUTOBOOST_PP_NODE_105(p) AUTOBOOST_PP_IIF(p##(105), 105, 106)
#                            define AUTOBOOST_PP_NODE_107(p) AUTOBOOST_PP_IIF(p##(107), 107, 108)
#                        define AUTOBOOST_PP_NODE_110(p) AUTOBOOST_PP_IIF(p##(110), AUTOBOOST_PP_NODE_109, AUTOBOOST_PP_NODE_111)
#                            define AUTOBOOST_PP_NODE_109(p) AUTOBOOST_PP_IIF(p##(109), 109, 110)
#                            define AUTOBOOST_PP_NODE_111(p) AUTOBOOST_PP_IIF(p##(111), 111, 112)
#                define AUTOBOOST_PP_NODE_120(p) AUTOBOOST_PP_IIF(p##(120), AUTOBOOST_PP_NODE_116, AUTOBOOST_PP_NODE_124)
#                    define AUTOBOOST_PP_NODE_116(p) AUTOBOOST_PP_IIF(p##(116), AUTOBOOST_PP_NODE_114, AUTOBOOST_PP_NODE_118)
#                        define AUTOBOOST_PP_NODE_114(p) AUTOBOOST_PP_IIF(p##(114), AUTOBOOST_PP_NODE_113, AUTOBOOST_PP_NODE_115)
#                            define AUTOBOOST_PP_NODE_113(p) AUTOBOOST_PP_IIF(p##(113), 113, 114)
#                            define AUTOBOOST_PP_NODE_115(p) AUTOBOOST_PP_IIF(p##(115), 115, 116)
#                        define AUTOBOOST_PP_NODE_118(p) AUTOBOOST_PP_IIF(p##(118), AUTOBOOST_PP_NODE_117, AUTOBOOST_PP_NODE_119)
#                            define AUTOBOOST_PP_NODE_117(p) AUTOBOOST_PP_IIF(p##(117), 117, 118)
#                            define AUTOBOOST_PP_NODE_119(p) AUTOBOOST_PP_IIF(p##(119), 119, 120)
#                    define AUTOBOOST_PP_NODE_124(p) AUTOBOOST_PP_IIF(p##(124), AUTOBOOST_PP_NODE_122, AUTOBOOST_PP_NODE_126)
#                        define AUTOBOOST_PP_NODE_122(p) AUTOBOOST_PP_IIF(p##(122), AUTOBOOST_PP_NODE_121, AUTOBOOST_PP_NODE_123)
#                            define AUTOBOOST_PP_NODE_121(p) AUTOBOOST_PP_IIF(p##(121), 121, 122)
#                            define AUTOBOOST_PP_NODE_123(p) AUTOBOOST_PP_IIF(p##(123), 123, 124)
#                        define AUTOBOOST_PP_NODE_126(p) AUTOBOOST_PP_IIF(p##(126), AUTOBOOST_PP_NODE_125, AUTOBOOST_PP_NODE_127)
#                            define AUTOBOOST_PP_NODE_125(p) AUTOBOOST_PP_IIF(p##(125), 125, 126)
#                            define AUTOBOOST_PP_NODE_127(p) AUTOBOOST_PP_IIF(p##(127), 127, 128)
#    define AUTOBOOST_PP_NODE_192(p) AUTOBOOST_PP_IIF(p##(192), AUTOBOOST_PP_NODE_160, AUTOBOOST_PP_NODE_224)
#        define AUTOBOOST_PP_NODE_160(p) AUTOBOOST_PP_IIF(p##(160), AUTOBOOST_PP_NODE_144, AUTOBOOST_PP_NODE_176)
#            define AUTOBOOST_PP_NODE_144(p) AUTOBOOST_PP_IIF(p##(144), AUTOBOOST_PP_NODE_136, AUTOBOOST_PP_NODE_152)
#                define AUTOBOOST_PP_NODE_136(p) AUTOBOOST_PP_IIF(p##(136), AUTOBOOST_PP_NODE_132, AUTOBOOST_PP_NODE_140)
#                    define AUTOBOOST_PP_NODE_132(p) AUTOBOOST_PP_IIF(p##(132), AUTOBOOST_PP_NODE_130, AUTOBOOST_PP_NODE_134)
#                        define AUTOBOOST_PP_NODE_130(p) AUTOBOOST_PP_IIF(p##(130), AUTOBOOST_PP_NODE_129, AUTOBOOST_PP_NODE_131)
#                            define AUTOBOOST_PP_NODE_129(p) AUTOBOOST_PP_IIF(p##(129), 129, 130)
#                            define AUTOBOOST_PP_NODE_131(p) AUTOBOOST_PP_IIF(p##(131), 131, 132)
#                        define AUTOBOOST_PP_NODE_134(p) AUTOBOOST_PP_IIF(p##(134), AUTOBOOST_PP_NODE_133, AUTOBOOST_PP_NODE_135)
#                            define AUTOBOOST_PP_NODE_133(p) AUTOBOOST_PP_IIF(p##(133), 133, 134)
#                            define AUTOBOOST_PP_NODE_135(p) AUTOBOOST_PP_IIF(p##(135), 135, 136)
#                    define AUTOBOOST_PP_NODE_140(p) AUTOBOOST_PP_IIF(p##(140), AUTOBOOST_PP_NODE_138, AUTOBOOST_PP_NODE_142)
#                        define AUTOBOOST_PP_NODE_138(p) AUTOBOOST_PP_IIF(p##(138), AUTOBOOST_PP_NODE_137, AUTOBOOST_PP_NODE_139)
#                            define AUTOBOOST_PP_NODE_137(p) AUTOBOOST_PP_IIF(p##(137), 137, 138)
#                            define AUTOBOOST_PP_NODE_139(p) AUTOBOOST_PP_IIF(p##(139), 139, 140)
#                        define AUTOBOOST_PP_NODE_142(p) AUTOBOOST_PP_IIF(p##(142), AUTOBOOST_PP_NODE_141, AUTOBOOST_PP_NODE_143)
#                            define AUTOBOOST_PP_NODE_141(p) AUTOBOOST_PP_IIF(p##(141), 141, 142)
#                            define AUTOBOOST_PP_NODE_143(p) AUTOBOOST_PP_IIF(p##(143), 143, 144)
#                define AUTOBOOST_PP_NODE_152(p) AUTOBOOST_PP_IIF(p##(152), AUTOBOOST_PP_NODE_148, AUTOBOOST_PP_NODE_156)
#                    define AUTOBOOST_PP_NODE_148(p) AUTOBOOST_PP_IIF(p##(148), AUTOBOOST_PP_NODE_146, AUTOBOOST_PP_NODE_150)
#                        define AUTOBOOST_PP_NODE_146(p) AUTOBOOST_PP_IIF(p##(146), AUTOBOOST_PP_NODE_145, AUTOBOOST_PP_NODE_147)
#                            define AUTOBOOST_PP_NODE_145(p) AUTOBOOST_PP_IIF(p##(145), 145, 146)
#                            define AUTOBOOST_PP_NODE_147(p) AUTOBOOST_PP_IIF(p##(147), 147, 148)
#                        define AUTOBOOST_PP_NODE_150(p) AUTOBOOST_PP_IIF(p##(150), AUTOBOOST_PP_NODE_149, AUTOBOOST_PP_NODE_151)
#                            define AUTOBOOST_PP_NODE_149(p) AUTOBOOST_PP_IIF(p##(149), 149, 150)
#                            define AUTOBOOST_PP_NODE_151(p) AUTOBOOST_PP_IIF(p##(151), 151, 152)
#                    define AUTOBOOST_PP_NODE_156(p) AUTOBOOST_PP_IIF(p##(156), AUTOBOOST_PP_NODE_154, AUTOBOOST_PP_NODE_158)
#                        define AUTOBOOST_PP_NODE_154(p) AUTOBOOST_PP_IIF(p##(154), AUTOBOOST_PP_NODE_153, AUTOBOOST_PP_NODE_155)
#                            define AUTOBOOST_PP_NODE_153(p) AUTOBOOST_PP_IIF(p##(153), 153, 154)
#                            define AUTOBOOST_PP_NODE_155(p) AUTOBOOST_PP_IIF(p##(155), 155, 156)
#                        define AUTOBOOST_PP_NODE_158(p) AUTOBOOST_PP_IIF(p##(158), AUTOBOOST_PP_NODE_157, AUTOBOOST_PP_NODE_159)
#                            define AUTOBOOST_PP_NODE_157(p) AUTOBOOST_PP_IIF(p##(157), 157, 158)
#                            define AUTOBOOST_PP_NODE_159(p) AUTOBOOST_PP_IIF(p##(159), 159, 160)
#            define AUTOBOOST_PP_NODE_176(p) AUTOBOOST_PP_IIF(p##(176), AUTOBOOST_PP_NODE_168, AUTOBOOST_PP_NODE_184)
#                define AUTOBOOST_PP_NODE_168(p) AUTOBOOST_PP_IIF(p##(168), AUTOBOOST_PP_NODE_164, AUTOBOOST_PP_NODE_172)
#                    define AUTOBOOST_PP_NODE_164(p) AUTOBOOST_PP_IIF(p##(164), AUTOBOOST_PP_NODE_162, AUTOBOOST_PP_NODE_166)
#                        define AUTOBOOST_PP_NODE_162(p) AUTOBOOST_PP_IIF(p##(162), AUTOBOOST_PP_NODE_161, AUTOBOOST_PP_NODE_163)
#                            define AUTOBOOST_PP_NODE_161(p) AUTOBOOST_PP_IIF(p##(161), 161, 162)
#                            define AUTOBOOST_PP_NODE_163(p) AUTOBOOST_PP_IIF(p##(163), 163, 164)
#                        define AUTOBOOST_PP_NODE_166(p) AUTOBOOST_PP_IIF(p##(166), AUTOBOOST_PP_NODE_165, AUTOBOOST_PP_NODE_167)
#                            define AUTOBOOST_PP_NODE_165(p) AUTOBOOST_PP_IIF(p##(165), 165, 166)
#                            define AUTOBOOST_PP_NODE_167(p) AUTOBOOST_PP_IIF(p##(167), 167, 168)
#                    define AUTOBOOST_PP_NODE_172(p) AUTOBOOST_PP_IIF(p##(172), AUTOBOOST_PP_NODE_170, AUTOBOOST_PP_NODE_174)
#                        define AUTOBOOST_PP_NODE_170(p) AUTOBOOST_PP_IIF(p##(170), AUTOBOOST_PP_NODE_169, AUTOBOOST_PP_NODE_171)
#                            define AUTOBOOST_PP_NODE_169(p) AUTOBOOST_PP_IIF(p##(169), 169, 170)
#                            define AUTOBOOST_PP_NODE_171(p) AUTOBOOST_PP_IIF(p##(171), 171, 172)
#                        define AUTOBOOST_PP_NODE_174(p) AUTOBOOST_PP_IIF(p##(174), AUTOBOOST_PP_NODE_173, AUTOBOOST_PP_NODE_175)
#                            define AUTOBOOST_PP_NODE_173(p) AUTOBOOST_PP_IIF(p##(173), 173, 174)
#                            define AUTOBOOST_PP_NODE_175(p) AUTOBOOST_PP_IIF(p##(175), 175, 176)
#                define AUTOBOOST_PP_NODE_184(p) AUTOBOOST_PP_IIF(p##(184), AUTOBOOST_PP_NODE_180, AUTOBOOST_PP_NODE_188)
#                    define AUTOBOOST_PP_NODE_180(p) AUTOBOOST_PP_IIF(p##(180), AUTOBOOST_PP_NODE_178, AUTOBOOST_PP_NODE_182)
#                        define AUTOBOOST_PP_NODE_178(p) AUTOBOOST_PP_IIF(p##(178), AUTOBOOST_PP_NODE_177, AUTOBOOST_PP_NODE_179)
#                            define AUTOBOOST_PP_NODE_177(p) AUTOBOOST_PP_IIF(p##(177), 177, 178)
#                            define AUTOBOOST_PP_NODE_179(p) AUTOBOOST_PP_IIF(p##(179), 179, 180)
#                        define AUTOBOOST_PP_NODE_182(p) AUTOBOOST_PP_IIF(p##(182), AUTOBOOST_PP_NODE_181, AUTOBOOST_PP_NODE_183)
#                            define AUTOBOOST_PP_NODE_181(p) AUTOBOOST_PP_IIF(p##(181), 181, 182)
#                            define AUTOBOOST_PP_NODE_183(p) AUTOBOOST_PP_IIF(p##(183), 183, 184)
#                    define AUTOBOOST_PP_NODE_188(p) AUTOBOOST_PP_IIF(p##(188), AUTOBOOST_PP_NODE_186, AUTOBOOST_PP_NODE_190)
#                        define AUTOBOOST_PP_NODE_186(p) AUTOBOOST_PP_IIF(p##(186), AUTOBOOST_PP_NODE_185, AUTOBOOST_PP_NODE_187)
#                            define AUTOBOOST_PP_NODE_185(p) AUTOBOOST_PP_IIF(p##(185), 185, 186)
#                            define AUTOBOOST_PP_NODE_187(p) AUTOBOOST_PP_IIF(p##(187), 187, 188)
#                        define AUTOBOOST_PP_NODE_190(p) AUTOBOOST_PP_IIF(p##(190), AUTOBOOST_PP_NODE_189, AUTOBOOST_PP_NODE_191)
#                            define AUTOBOOST_PP_NODE_189(p) AUTOBOOST_PP_IIF(p##(189), 189, 190)
#                            define AUTOBOOST_PP_NODE_191(p) AUTOBOOST_PP_IIF(p##(191), 191, 192)
#        define AUTOBOOST_PP_NODE_224(p) AUTOBOOST_PP_IIF(p##(224), AUTOBOOST_PP_NODE_208, AUTOBOOST_PP_NODE_240)
#            define AUTOBOOST_PP_NODE_208(p) AUTOBOOST_PP_IIF(p##(208), AUTOBOOST_PP_NODE_200, AUTOBOOST_PP_NODE_216)
#                define AUTOBOOST_PP_NODE_200(p) AUTOBOOST_PP_IIF(p##(200), AUTOBOOST_PP_NODE_196, AUTOBOOST_PP_NODE_204)
#                    define AUTOBOOST_PP_NODE_196(p) AUTOBOOST_PP_IIF(p##(196), AUTOBOOST_PP_NODE_194, AUTOBOOST_PP_NODE_198)
#                        define AUTOBOOST_PP_NODE_194(p) AUTOBOOST_PP_IIF(p##(194), AUTOBOOST_PP_NODE_193, AUTOBOOST_PP_NODE_195)
#                            define AUTOBOOST_PP_NODE_193(p) AUTOBOOST_PP_IIF(p##(193), 193, 194)
#                            define AUTOBOOST_PP_NODE_195(p) AUTOBOOST_PP_IIF(p##(195), 195, 196)
#                        define AUTOBOOST_PP_NODE_198(p) AUTOBOOST_PP_IIF(p##(198), AUTOBOOST_PP_NODE_197, AUTOBOOST_PP_NODE_199)
#                            define AUTOBOOST_PP_NODE_197(p) AUTOBOOST_PP_IIF(p##(197), 197, 198)
#                            define AUTOBOOST_PP_NODE_199(p) AUTOBOOST_PP_IIF(p##(199), 199, 200)
#                    define AUTOBOOST_PP_NODE_204(p) AUTOBOOST_PP_IIF(p##(204), AUTOBOOST_PP_NODE_202, AUTOBOOST_PP_NODE_206)
#                        define AUTOBOOST_PP_NODE_202(p) AUTOBOOST_PP_IIF(p##(202), AUTOBOOST_PP_NODE_201, AUTOBOOST_PP_NODE_203)
#                            define AUTOBOOST_PP_NODE_201(p) AUTOBOOST_PP_IIF(p##(201), 201, 202)
#                            define AUTOBOOST_PP_NODE_203(p) AUTOBOOST_PP_IIF(p##(203), 203, 204)
#                        define AUTOBOOST_PP_NODE_206(p) AUTOBOOST_PP_IIF(p##(206), AUTOBOOST_PP_NODE_205, AUTOBOOST_PP_NODE_207)
#                            define AUTOBOOST_PP_NODE_205(p) AUTOBOOST_PP_IIF(p##(205), 205, 206)
#                            define AUTOBOOST_PP_NODE_207(p) AUTOBOOST_PP_IIF(p##(207), 207, 208)
#                define AUTOBOOST_PP_NODE_216(p) AUTOBOOST_PP_IIF(p##(216), AUTOBOOST_PP_NODE_212, AUTOBOOST_PP_NODE_220)
#                    define AUTOBOOST_PP_NODE_212(p) AUTOBOOST_PP_IIF(p##(212), AUTOBOOST_PP_NODE_210, AUTOBOOST_PP_NODE_214)
#                        define AUTOBOOST_PP_NODE_210(p) AUTOBOOST_PP_IIF(p##(210), AUTOBOOST_PP_NODE_209, AUTOBOOST_PP_NODE_211)
#                            define AUTOBOOST_PP_NODE_209(p) AUTOBOOST_PP_IIF(p##(209), 209, 210)
#                            define AUTOBOOST_PP_NODE_211(p) AUTOBOOST_PP_IIF(p##(211), 211, 212)
#                        define AUTOBOOST_PP_NODE_214(p) AUTOBOOST_PP_IIF(p##(214), AUTOBOOST_PP_NODE_213, AUTOBOOST_PP_NODE_215)
#                            define AUTOBOOST_PP_NODE_213(p) AUTOBOOST_PP_IIF(p##(213), 213, 214)
#                            define AUTOBOOST_PP_NODE_215(p) AUTOBOOST_PP_IIF(p##(215), 215, 216)
#                    define AUTOBOOST_PP_NODE_220(p) AUTOBOOST_PP_IIF(p##(220), AUTOBOOST_PP_NODE_218, AUTOBOOST_PP_NODE_222)
#                        define AUTOBOOST_PP_NODE_218(p) AUTOBOOST_PP_IIF(p##(218), AUTOBOOST_PP_NODE_217, AUTOBOOST_PP_NODE_219)
#                            define AUTOBOOST_PP_NODE_217(p) AUTOBOOST_PP_IIF(p##(217), 217, 218)
#                            define AUTOBOOST_PP_NODE_219(p) AUTOBOOST_PP_IIF(p##(219), 219, 220)
#                        define AUTOBOOST_PP_NODE_222(p) AUTOBOOST_PP_IIF(p##(222), AUTOBOOST_PP_NODE_221, AUTOBOOST_PP_NODE_223)
#                            define AUTOBOOST_PP_NODE_221(p) AUTOBOOST_PP_IIF(p##(221), 221, 222)
#                            define AUTOBOOST_PP_NODE_223(p) AUTOBOOST_PP_IIF(p##(223), 223, 224)
#            define AUTOBOOST_PP_NODE_240(p) AUTOBOOST_PP_IIF(p##(240), AUTOBOOST_PP_NODE_232, AUTOBOOST_PP_NODE_248)
#                define AUTOBOOST_PP_NODE_232(p) AUTOBOOST_PP_IIF(p##(232), AUTOBOOST_PP_NODE_228, AUTOBOOST_PP_NODE_236)
#                    define AUTOBOOST_PP_NODE_228(p) AUTOBOOST_PP_IIF(p##(228), AUTOBOOST_PP_NODE_226, AUTOBOOST_PP_NODE_230)
#                        define AUTOBOOST_PP_NODE_226(p) AUTOBOOST_PP_IIF(p##(226), AUTOBOOST_PP_NODE_225, AUTOBOOST_PP_NODE_227)
#                            define AUTOBOOST_PP_NODE_225(p) AUTOBOOST_PP_IIF(p##(225), 225, 226)
#                            define AUTOBOOST_PP_NODE_227(p) AUTOBOOST_PP_IIF(p##(227), 227, 228)
#                        define AUTOBOOST_PP_NODE_230(p) AUTOBOOST_PP_IIF(p##(230), AUTOBOOST_PP_NODE_229, AUTOBOOST_PP_NODE_231)
#                            define AUTOBOOST_PP_NODE_229(p) AUTOBOOST_PP_IIF(p##(229), 229, 230)
#                            define AUTOBOOST_PP_NODE_231(p) AUTOBOOST_PP_IIF(p##(231), 231, 232)
#                    define AUTOBOOST_PP_NODE_236(p) AUTOBOOST_PP_IIF(p##(236), AUTOBOOST_PP_NODE_234, AUTOBOOST_PP_NODE_238)
#                        define AUTOBOOST_PP_NODE_234(p) AUTOBOOST_PP_IIF(p##(234), AUTOBOOST_PP_NODE_233, AUTOBOOST_PP_NODE_235)
#                            define AUTOBOOST_PP_NODE_233(p) AUTOBOOST_PP_IIF(p##(233), 233, 234)
#                            define AUTOBOOST_PP_NODE_235(p) AUTOBOOST_PP_IIF(p##(235), 235, 236)
#                        define AUTOBOOST_PP_NODE_238(p) AUTOBOOST_PP_IIF(p##(238), AUTOBOOST_PP_NODE_237, AUTOBOOST_PP_NODE_239)
#                            define AUTOBOOST_PP_NODE_237(p) AUTOBOOST_PP_IIF(p##(237), 237, 238)
#                            define AUTOBOOST_PP_NODE_239(p) AUTOBOOST_PP_IIF(p##(239), 239, 240)
#                define AUTOBOOST_PP_NODE_248(p) AUTOBOOST_PP_IIF(p##(248), AUTOBOOST_PP_NODE_244, AUTOBOOST_PP_NODE_252)
#                    define AUTOBOOST_PP_NODE_244(p) AUTOBOOST_PP_IIF(p##(244), AUTOBOOST_PP_NODE_242, AUTOBOOST_PP_NODE_246)
#                        define AUTOBOOST_PP_NODE_242(p) AUTOBOOST_PP_IIF(p##(242), AUTOBOOST_PP_NODE_241, AUTOBOOST_PP_NODE_243)
#                            define AUTOBOOST_PP_NODE_241(p) AUTOBOOST_PP_IIF(p##(241), 241, 242)
#                            define AUTOBOOST_PP_NODE_243(p) AUTOBOOST_PP_IIF(p##(243), 243, 244)
#                        define AUTOBOOST_PP_NODE_246(p) AUTOBOOST_PP_IIF(p##(246), AUTOBOOST_PP_NODE_245, AUTOBOOST_PP_NODE_247)
#                            define AUTOBOOST_PP_NODE_245(p) AUTOBOOST_PP_IIF(p##(245), 245, 246)
#                            define AUTOBOOST_PP_NODE_247(p) AUTOBOOST_PP_IIF(p##(247), 247, 248)
#                    define AUTOBOOST_PP_NODE_252(p) AUTOBOOST_PP_IIF(p##(252), AUTOBOOST_PP_NODE_250, AUTOBOOST_PP_NODE_254)
#                        define AUTOBOOST_PP_NODE_250(p) AUTOBOOST_PP_IIF(p##(250), AUTOBOOST_PP_NODE_249, AUTOBOOST_PP_NODE_251)
#                            define AUTOBOOST_PP_NODE_249(p) AUTOBOOST_PP_IIF(p##(249), 249, 250)
#                            define AUTOBOOST_PP_NODE_251(p) AUTOBOOST_PP_IIF(p##(251), 251, 252)
#                        define AUTOBOOST_PP_NODE_254(p) AUTOBOOST_PP_IIF(p##(254), AUTOBOOST_PP_NODE_253, AUTOBOOST_PP_NODE_255)
#                            define AUTOBOOST_PP_NODE_253(p) AUTOBOOST_PP_IIF(p##(253), 253, 254)
#                            define AUTOBOOST_PP_NODE_255(p) AUTOBOOST_PP_IIF(p##(255), 255, 256)
#
# endif
