# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.
#  *     Distributed under the Boost Software License, Version 1.0. (See
#  *     accompanying file LICENSE_1_0.txt or copy at
#  *     http://www.boost.org/LICENSE_1_0.txt)
#  *                                                                          *
#  ************************************************************************** */
#
# /* See http://www.boost.org for most recent version. */
#
# ifndef AUTOBOOST_PREPROCESSOR_SEQ_DETAIL_SPLIT_HPP
# define AUTOBOOST_PREPROCESSOR_SEQ_DETAIL_SPLIT_HPP
#
# include <autoboost/preprocessor/config/config.hpp>
#
# /* AUTOBOOST_PP_SEQ_SPLIT */
#
# define AUTOBOOST_PP_SEQ_SPLIT(n, seq) AUTOBOOST_PP_SEQ_SPLIT_D(n, seq)
#
# if ~AUTOBOOST_PP_CONFIG_FLAGS() & AUTOBOOST_PP_CONFIG_MWCC()
#    define AUTOBOOST_PP_SEQ_SPLIT_D(n, seq) (AUTOBOOST_PP_SEQ_SPLIT_ ## n seq)
# else
#    define AUTOBOOST_PP_SEQ_SPLIT_D(n, seq) (AUTOBOOST_PP_SEQ_SPLIT_ ## n ## seq)
# endif
#
# define AUTOBOOST_PP_SEQ_SPLIT_1(x) (x),
# define AUTOBOOST_PP_SEQ_SPLIT_2(x) (x) AUTOBOOST_PP_SEQ_SPLIT_1
# define AUTOBOOST_PP_SEQ_SPLIT_3(x) (x) AUTOBOOST_PP_SEQ_SPLIT_2
# define AUTOBOOST_PP_SEQ_SPLIT_4(x) (x) AUTOBOOST_PP_SEQ_SPLIT_3
# define AUTOBOOST_PP_SEQ_SPLIT_5(x) (x) AUTOBOOST_PP_SEQ_SPLIT_4
# define AUTOBOOST_PP_SEQ_SPLIT_6(x) (x) AUTOBOOST_PP_SEQ_SPLIT_5
# define AUTOBOOST_PP_SEQ_SPLIT_7(x) (x) AUTOBOOST_PP_SEQ_SPLIT_6
# define AUTOBOOST_PP_SEQ_SPLIT_8(x) (x) AUTOBOOST_PP_SEQ_SPLIT_7
# define AUTOBOOST_PP_SEQ_SPLIT_9(x) (x) AUTOBOOST_PP_SEQ_SPLIT_8
# define AUTOBOOST_PP_SEQ_SPLIT_10(x) (x) AUTOBOOST_PP_SEQ_SPLIT_9
# define AUTOBOOST_PP_SEQ_SPLIT_11(x) (x) AUTOBOOST_PP_SEQ_SPLIT_10
# define AUTOBOOST_PP_SEQ_SPLIT_12(x) (x) AUTOBOOST_PP_SEQ_SPLIT_11
# define AUTOBOOST_PP_SEQ_SPLIT_13(x) (x) AUTOBOOST_PP_SEQ_SPLIT_12
# define AUTOBOOST_PP_SEQ_SPLIT_14(x) (x) AUTOBOOST_PP_SEQ_SPLIT_13
# define AUTOBOOST_PP_SEQ_SPLIT_15(x) (x) AUTOBOOST_PP_SEQ_SPLIT_14
# define AUTOBOOST_PP_SEQ_SPLIT_16(x) (x) AUTOBOOST_PP_SEQ_SPLIT_15
# define AUTOBOOST_PP_SEQ_SPLIT_17(x) (x) AUTOBOOST_PP_SEQ_SPLIT_16
# define AUTOBOOST_PP_SEQ_SPLIT_18(x) (x) AUTOBOOST_PP_SEQ_SPLIT_17
# define AUTOBOOST_PP_SEQ_SPLIT_19(x) (x) AUTOBOOST_PP_SEQ_SPLIT_18
# define AUTOBOOST_PP_SEQ_SPLIT_20(x) (x) AUTOBOOST_PP_SEQ_SPLIT_19
# define AUTOBOOST_PP_SEQ_SPLIT_21(x) (x) AUTOBOOST_PP_SEQ_SPLIT_20
# define AUTOBOOST_PP_SEQ_SPLIT_22(x) (x) AUTOBOOST_PP_SEQ_SPLIT_21
# define AUTOBOOST_PP_SEQ_SPLIT_23(x) (x) AUTOBOOST_PP_SEQ_SPLIT_22
# define AUTOBOOST_PP_SEQ_SPLIT_24(x) (x) AUTOBOOST_PP_SEQ_SPLIT_23
# define AUTOBOOST_PP_SEQ_SPLIT_25(x) (x) AUTOBOOST_PP_SEQ_SPLIT_24
# define AUTOBOOST_PP_SEQ_SPLIT_26(x) (x) AUTOBOOST_PP_SEQ_SPLIT_25
# define AUTOBOOST_PP_SEQ_SPLIT_27(x) (x) AUTOBOOST_PP_SEQ_SPLIT_26
# define AUTOBOOST_PP_SEQ_SPLIT_28(x) (x) AUTOBOOST_PP_SEQ_SPLIT_27
# define AUTOBOOST_PP_SEQ_SPLIT_29(x) (x) AUTOBOOST_PP_SEQ_SPLIT_28
# define AUTOBOOST_PP_SEQ_SPLIT_30(x) (x) AUTOBOOST_PP_SEQ_SPLIT_29
# define AUTOBOOST_PP_SEQ_SPLIT_31(x) (x) AUTOBOOST_PP_SEQ_SPLIT_30
# define AUTOBOOST_PP_SEQ_SPLIT_32(x) (x) AUTOBOOST_PP_SEQ_SPLIT_31
# define AUTOBOOST_PP_SEQ_SPLIT_33(x) (x) AUTOBOOST_PP_SEQ_SPLIT_32
# define AUTOBOOST_PP_SEQ_SPLIT_34(x) (x) AUTOBOOST_PP_SEQ_SPLIT_33
# define AUTOBOOST_PP_SEQ_SPLIT_35(x) (x) AUTOBOOST_PP_SEQ_SPLIT_34
# define AUTOBOOST_PP_SEQ_SPLIT_36(x) (x) AUTOBOOST_PP_SEQ_SPLIT_35
# define AUTOBOOST_PP_SEQ_SPLIT_37(x) (x) AUTOBOOST_PP_SEQ_SPLIT_36
# define AUTOBOOST_PP_SEQ_SPLIT_38(x) (x) AUTOBOOST_PP_SEQ_SPLIT_37
# define AUTOBOOST_PP_SEQ_SPLIT_39(x) (x) AUTOBOOST_PP_SEQ_SPLIT_38
# define AUTOBOOST_PP_SEQ_SPLIT_40(x) (x) AUTOBOOST_PP_SEQ_SPLIT_39
# define AUTOBOOST_PP_SEQ_SPLIT_41(x) (x) AUTOBOOST_PP_SEQ_SPLIT_40
# define AUTOBOOST_PP_SEQ_SPLIT_42(x) (x) AUTOBOOST_PP_SEQ_SPLIT_41
# define AUTOBOOST_PP_SEQ_SPLIT_43(x) (x) AUTOBOOST_PP_SEQ_SPLIT_42
# define AUTOBOOST_PP_SEQ_SPLIT_44(x) (x) AUTOBOOST_PP_SEQ_SPLIT_43
# define AUTOBOOST_PP_SEQ_SPLIT_45(x) (x) AUTOBOOST_PP_SEQ_SPLIT_44
# define AUTOBOOST_PP_SEQ_SPLIT_46(x) (x) AUTOBOOST_PP_SEQ_SPLIT_45
# define AUTOBOOST_PP_SEQ_SPLIT_47(x) (x) AUTOBOOST_PP_SEQ_SPLIT_46
# define AUTOBOOST_PP_SEQ_SPLIT_48(x) (x) AUTOBOOST_PP_SEQ_SPLIT_47
# define AUTOBOOST_PP_SEQ_SPLIT_49(x) (x) AUTOBOOST_PP_SEQ_SPLIT_48
# define AUTOBOOST_PP_SEQ_SPLIT_50(x) (x) AUTOBOOST_PP_SEQ_SPLIT_49
# define AUTOBOOST_PP_SEQ_SPLIT_51(x) (x) AUTOBOOST_PP_SEQ_SPLIT_50
# define AUTOBOOST_PP_SEQ_SPLIT_52(x) (x) AUTOBOOST_PP_SEQ_SPLIT_51
# define AUTOBOOST_PP_SEQ_SPLIT_53(x) (x) AUTOBOOST_PP_SEQ_SPLIT_52
# define AUTOBOOST_PP_SEQ_SPLIT_54(x) (x) AUTOBOOST_PP_SEQ_SPLIT_53
# define AUTOBOOST_PP_SEQ_SPLIT_55(x) (x) AUTOBOOST_PP_SEQ_SPLIT_54
# define AUTOBOOST_PP_SEQ_SPLIT_56(x) (x) AUTOBOOST_PP_SEQ_SPLIT_55
# define AUTOBOOST_PP_SEQ_SPLIT_57(x) (x) AUTOBOOST_PP_SEQ_SPLIT_56
# define AUTOBOOST_PP_SEQ_SPLIT_58(x) (x) AUTOBOOST_PP_SEQ_SPLIT_57
# define AUTOBOOST_PP_SEQ_SPLIT_59(x) (x) AUTOBOOST_PP_SEQ_SPLIT_58
# define AUTOBOOST_PP_SEQ_SPLIT_60(x) (x) AUTOBOOST_PP_SEQ_SPLIT_59
# define AUTOBOOST_PP_SEQ_SPLIT_61(x) (x) AUTOBOOST_PP_SEQ_SPLIT_60
# define AUTOBOOST_PP_SEQ_SPLIT_62(x) (x) AUTOBOOST_PP_SEQ_SPLIT_61
# define AUTOBOOST_PP_SEQ_SPLIT_63(x) (x) AUTOBOOST_PP_SEQ_SPLIT_62
# define AUTOBOOST_PP_SEQ_SPLIT_64(x) (x) AUTOBOOST_PP_SEQ_SPLIT_63
# define AUTOBOOST_PP_SEQ_SPLIT_65(x) (x) AUTOBOOST_PP_SEQ_SPLIT_64
# define AUTOBOOST_PP_SEQ_SPLIT_66(x) (x) AUTOBOOST_PP_SEQ_SPLIT_65
# define AUTOBOOST_PP_SEQ_SPLIT_67(x) (x) AUTOBOOST_PP_SEQ_SPLIT_66
# define AUTOBOOST_PP_SEQ_SPLIT_68(x) (x) AUTOBOOST_PP_SEQ_SPLIT_67
# define AUTOBOOST_PP_SEQ_SPLIT_69(x) (x) AUTOBOOST_PP_SEQ_SPLIT_68
# define AUTOBOOST_PP_SEQ_SPLIT_70(x) (x) AUTOBOOST_PP_SEQ_SPLIT_69
# define AUTOBOOST_PP_SEQ_SPLIT_71(x) (x) AUTOBOOST_PP_SEQ_SPLIT_70
# define AUTOBOOST_PP_SEQ_SPLIT_72(x) (x) AUTOBOOST_PP_SEQ_SPLIT_71
# define AUTOBOOST_PP_SEQ_SPLIT_73(x) (x) AUTOBOOST_PP_SEQ_SPLIT_72
# define AUTOBOOST_PP_SEQ_SPLIT_74(x) (x) AUTOBOOST_PP_SEQ_SPLIT_73
# define AUTOBOOST_PP_SEQ_SPLIT_75(x) (x) AUTOBOOST_PP_SEQ_SPLIT_74
# define AUTOBOOST_PP_SEQ_SPLIT_76(x) (x) AUTOBOOST_PP_SEQ_SPLIT_75
# define AUTOBOOST_PP_SEQ_SPLIT_77(x) (x) AUTOBOOST_PP_SEQ_SPLIT_76
# define AUTOBOOST_PP_SEQ_SPLIT_78(x) (x) AUTOBOOST_PP_SEQ_SPLIT_77
# define AUTOBOOST_PP_SEQ_SPLIT_79(x) (x) AUTOBOOST_PP_SEQ_SPLIT_78
# define AUTOBOOST_PP_SEQ_SPLIT_80(x) (x) AUTOBOOST_PP_SEQ_SPLIT_79
# define AUTOBOOST_PP_SEQ_SPLIT_81(x) (x) AUTOBOOST_PP_SEQ_SPLIT_80
# define AUTOBOOST_PP_SEQ_SPLIT_82(x) (x) AUTOBOOST_PP_SEQ_SPLIT_81
# define AUTOBOOST_PP_SEQ_SPLIT_83(x) (x) AUTOBOOST_PP_SEQ_SPLIT_82
# define AUTOBOOST_PP_SEQ_SPLIT_84(x) (x) AUTOBOOST_PP_SEQ_SPLIT_83
# define AUTOBOOST_PP_SEQ_SPLIT_85(x) (x) AUTOBOOST_PP_SEQ_SPLIT_84
# define AUTOBOOST_PP_SEQ_SPLIT_86(x) (x) AUTOBOOST_PP_SEQ_SPLIT_85
# define AUTOBOOST_PP_SEQ_SPLIT_87(x) (x) AUTOBOOST_PP_SEQ_SPLIT_86
# define AUTOBOOST_PP_SEQ_SPLIT_88(x) (x) AUTOBOOST_PP_SEQ_SPLIT_87
# define AUTOBOOST_PP_SEQ_SPLIT_89(x) (x) AUTOBOOST_PP_SEQ_SPLIT_88
# define AUTOBOOST_PP_SEQ_SPLIT_90(x) (x) AUTOBOOST_PP_SEQ_SPLIT_89
# define AUTOBOOST_PP_SEQ_SPLIT_91(x) (x) AUTOBOOST_PP_SEQ_SPLIT_90
# define AUTOBOOST_PP_SEQ_SPLIT_92(x) (x) AUTOBOOST_PP_SEQ_SPLIT_91
# define AUTOBOOST_PP_SEQ_SPLIT_93(x) (x) AUTOBOOST_PP_SEQ_SPLIT_92
# define AUTOBOOST_PP_SEQ_SPLIT_94(x) (x) AUTOBOOST_PP_SEQ_SPLIT_93
# define AUTOBOOST_PP_SEQ_SPLIT_95(x) (x) AUTOBOOST_PP_SEQ_SPLIT_94
# define AUTOBOOST_PP_SEQ_SPLIT_96(x) (x) AUTOBOOST_PP_SEQ_SPLIT_95
# define AUTOBOOST_PP_SEQ_SPLIT_97(x) (x) AUTOBOOST_PP_SEQ_SPLIT_96
# define AUTOBOOST_PP_SEQ_SPLIT_98(x) (x) AUTOBOOST_PP_SEQ_SPLIT_97
# define AUTOBOOST_PP_SEQ_SPLIT_99(x) (x) AUTOBOOST_PP_SEQ_SPLIT_98
# define AUTOBOOST_PP_SEQ_SPLIT_100(x) (x) AUTOBOOST_PP_SEQ_SPLIT_99
# define AUTOBOOST_PP_SEQ_SPLIT_101(x) (x) AUTOBOOST_PP_SEQ_SPLIT_100
# define AUTOBOOST_PP_SEQ_SPLIT_102(x) (x) AUTOBOOST_PP_SEQ_SPLIT_101
# define AUTOBOOST_PP_SEQ_SPLIT_103(x) (x) AUTOBOOST_PP_SEQ_SPLIT_102
# define AUTOBOOST_PP_SEQ_SPLIT_104(x) (x) AUTOBOOST_PP_SEQ_SPLIT_103
# define AUTOBOOST_PP_SEQ_SPLIT_105(x) (x) AUTOBOOST_PP_SEQ_SPLIT_104
# define AUTOBOOST_PP_SEQ_SPLIT_106(x) (x) AUTOBOOST_PP_SEQ_SPLIT_105
# define AUTOBOOST_PP_SEQ_SPLIT_107(x) (x) AUTOBOOST_PP_SEQ_SPLIT_106
# define AUTOBOOST_PP_SEQ_SPLIT_108(x) (x) AUTOBOOST_PP_SEQ_SPLIT_107
# define AUTOBOOST_PP_SEQ_SPLIT_109(x) (x) AUTOBOOST_PP_SEQ_SPLIT_108
# define AUTOBOOST_PP_SEQ_SPLIT_110(x) (x) AUTOBOOST_PP_SEQ_SPLIT_109
# define AUTOBOOST_PP_SEQ_SPLIT_111(x) (x) AUTOBOOST_PP_SEQ_SPLIT_110
# define AUTOBOOST_PP_SEQ_SPLIT_112(x) (x) AUTOBOOST_PP_SEQ_SPLIT_111
# define AUTOBOOST_PP_SEQ_SPLIT_113(x) (x) AUTOBOOST_PP_SEQ_SPLIT_112
# define AUTOBOOST_PP_SEQ_SPLIT_114(x) (x) AUTOBOOST_PP_SEQ_SPLIT_113
# define AUTOBOOST_PP_SEQ_SPLIT_115(x) (x) AUTOBOOST_PP_SEQ_SPLIT_114
# define AUTOBOOST_PP_SEQ_SPLIT_116(x) (x) AUTOBOOST_PP_SEQ_SPLIT_115
# define AUTOBOOST_PP_SEQ_SPLIT_117(x) (x) AUTOBOOST_PP_SEQ_SPLIT_116
# define AUTOBOOST_PP_SEQ_SPLIT_118(x) (x) AUTOBOOST_PP_SEQ_SPLIT_117
# define AUTOBOOST_PP_SEQ_SPLIT_119(x) (x) AUTOBOOST_PP_SEQ_SPLIT_118
# define AUTOBOOST_PP_SEQ_SPLIT_120(x) (x) AUTOBOOST_PP_SEQ_SPLIT_119
# define AUTOBOOST_PP_SEQ_SPLIT_121(x) (x) AUTOBOOST_PP_SEQ_SPLIT_120
# define AUTOBOOST_PP_SEQ_SPLIT_122(x) (x) AUTOBOOST_PP_SEQ_SPLIT_121
# define AUTOBOOST_PP_SEQ_SPLIT_123(x) (x) AUTOBOOST_PP_SEQ_SPLIT_122
# define AUTOBOOST_PP_SEQ_SPLIT_124(x) (x) AUTOBOOST_PP_SEQ_SPLIT_123
# define AUTOBOOST_PP_SEQ_SPLIT_125(x) (x) AUTOBOOST_PP_SEQ_SPLIT_124
# define AUTOBOOST_PP_SEQ_SPLIT_126(x) (x) AUTOBOOST_PP_SEQ_SPLIT_125
# define AUTOBOOST_PP_SEQ_SPLIT_127(x) (x) AUTOBOOST_PP_SEQ_SPLIT_126
# define AUTOBOOST_PP_SEQ_SPLIT_128(x) (x) AUTOBOOST_PP_SEQ_SPLIT_127
# define AUTOBOOST_PP_SEQ_SPLIT_129(x) (x) AUTOBOOST_PP_SEQ_SPLIT_128
# define AUTOBOOST_PP_SEQ_SPLIT_130(x) (x) AUTOBOOST_PP_SEQ_SPLIT_129
# define AUTOBOOST_PP_SEQ_SPLIT_131(x) (x) AUTOBOOST_PP_SEQ_SPLIT_130
# define AUTOBOOST_PP_SEQ_SPLIT_132(x) (x) AUTOBOOST_PP_SEQ_SPLIT_131
# define AUTOBOOST_PP_SEQ_SPLIT_133(x) (x) AUTOBOOST_PP_SEQ_SPLIT_132
# define AUTOBOOST_PP_SEQ_SPLIT_134(x) (x) AUTOBOOST_PP_SEQ_SPLIT_133
# define AUTOBOOST_PP_SEQ_SPLIT_135(x) (x) AUTOBOOST_PP_SEQ_SPLIT_134
# define AUTOBOOST_PP_SEQ_SPLIT_136(x) (x) AUTOBOOST_PP_SEQ_SPLIT_135
# define AUTOBOOST_PP_SEQ_SPLIT_137(x) (x) AUTOBOOST_PP_SEQ_SPLIT_136
# define AUTOBOOST_PP_SEQ_SPLIT_138(x) (x) AUTOBOOST_PP_SEQ_SPLIT_137
# define AUTOBOOST_PP_SEQ_SPLIT_139(x) (x) AUTOBOOST_PP_SEQ_SPLIT_138
# define AUTOBOOST_PP_SEQ_SPLIT_140(x) (x) AUTOBOOST_PP_SEQ_SPLIT_139
# define AUTOBOOST_PP_SEQ_SPLIT_141(x) (x) AUTOBOOST_PP_SEQ_SPLIT_140
# define AUTOBOOST_PP_SEQ_SPLIT_142(x) (x) AUTOBOOST_PP_SEQ_SPLIT_141
# define AUTOBOOST_PP_SEQ_SPLIT_143(x) (x) AUTOBOOST_PP_SEQ_SPLIT_142
# define AUTOBOOST_PP_SEQ_SPLIT_144(x) (x) AUTOBOOST_PP_SEQ_SPLIT_143
# define AUTOBOOST_PP_SEQ_SPLIT_145(x) (x) AUTOBOOST_PP_SEQ_SPLIT_144
# define AUTOBOOST_PP_SEQ_SPLIT_146(x) (x) AUTOBOOST_PP_SEQ_SPLIT_145
# define AUTOBOOST_PP_SEQ_SPLIT_147(x) (x) AUTOBOOST_PP_SEQ_SPLIT_146
# define AUTOBOOST_PP_SEQ_SPLIT_148(x) (x) AUTOBOOST_PP_SEQ_SPLIT_147
# define AUTOBOOST_PP_SEQ_SPLIT_149(x) (x) AUTOBOOST_PP_SEQ_SPLIT_148
# define AUTOBOOST_PP_SEQ_SPLIT_150(x) (x) AUTOBOOST_PP_SEQ_SPLIT_149
# define AUTOBOOST_PP_SEQ_SPLIT_151(x) (x) AUTOBOOST_PP_SEQ_SPLIT_150
# define AUTOBOOST_PP_SEQ_SPLIT_152(x) (x) AUTOBOOST_PP_SEQ_SPLIT_151
# define AUTOBOOST_PP_SEQ_SPLIT_153(x) (x) AUTOBOOST_PP_SEQ_SPLIT_152
# define AUTOBOOST_PP_SEQ_SPLIT_154(x) (x) AUTOBOOST_PP_SEQ_SPLIT_153
# define AUTOBOOST_PP_SEQ_SPLIT_155(x) (x) AUTOBOOST_PP_SEQ_SPLIT_154
# define AUTOBOOST_PP_SEQ_SPLIT_156(x) (x) AUTOBOOST_PP_SEQ_SPLIT_155
# define AUTOBOOST_PP_SEQ_SPLIT_157(x) (x) AUTOBOOST_PP_SEQ_SPLIT_156
# define AUTOBOOST_PP_SEQ_SPLIT_158(x) (x) AUTOBOOST_PP_SEQ_SPLIT_157
# define AUTOBOOST_PP_SEQ_SPLIT_159(x) (x) AUTOBOOST_PP_SEQ_SPLIT_158
# define AUTOBOOST_PP_SEQ_SPLIT_160(x) (x) AUTOBOOST_PP_SEQ_SPLIT_159
# define AUTOBOOST_PP_SEQ_SPLIT_161(x) (x) AUTOBOOST_PP_SEQ_SPLIT_160
# define AUTOBOOST_PP_SEQ_SPLIT_162(x) (x) AUTOBOOST_PP_SEQ_SPLIT_161
# define AUTOBOOST_PP_SEQ_SPLIT_163(x) (x) AUTOBOOST_PP_SEQ_SPLIT_162
# define AUTOBOOST_PP_SEQ_SPLIT_164(x) (x) AUTOBOOST_PP_SEQ_SPLIT_163
# define AUTOBOOST_PP_SEQ_SPLIT_165(x) (x) AUTOBOOST_PP_SEQ_SPLIT_164
# define AUTOBOOST_PP_SEQ_SPLIT_166(x) (x) AUTOBOOST_PP_SEQ_SPLIT_165
# define AUTOBOOST_PP_SEQ_SPLIT_167(x) (x) AUTOBOOST_PP_SEQ_SPLIT_166
# define AUTOBOOST_PP_SEQ_SPLIT_168(x) (x) AUTOBOOST_PP_SEQ_SPLIT_167
# define AUTOBOOST_PP_SEQ_SPLIT_169(x) (x) AUTOBOOST_PP_SEQ_SPLIT_168
# define AUTOBOOST_PP_SEQ_SPLIT_170(x) (x) AUTOBOOST_PP_SEQ_SPLIT_169
# define AUTOBOOST_PP_SEQ_SPLIT_171(x) (x) AUTOBOOST_PP_SEQ_SPLIT_170
# define AUTOBOOST_PP_SEQ_SPLIT_172(x) (x) AUTOBOOST_PP_SEQ_SPLIT_171
# define AUTOBOOST_PP_SEQ_SPLIT_173(x) (x) AUTOBOOST_PP_SEQ_SPLIT_172
# define AUTOBOOST_PP_SEQ_SPLIT_174(x) (x) AUTOBOOST_PP_SEQ_SPLIT_173
# define AUTOBOOST_PP_SEQ_SPLIT_175(x) (x) AUTOBOOST_PP_SEQ_SPLIT_174
# define AUTOBOOST_PP_SEQ_SPLIT_176(x) (x) AUTOBOOST_PP_SEQ_SPLIT_175
# define AUTOBOOST_PP_SEQ_SPLIT_177(x) (x) AUTOBOOST_PP_SEQ_SPLIT_176
# define AUTOBOOST_PP_SEQ_SPLIT_178(x) (x) AUTOBOOST_PP_SEQ_SPLIT_177
# define AUTOBOOST_PP_SEQ_SPLIT_179(x) (x) AUTOBOOST_PP_SEQ_SPLIT_178
# define AUTOBOOST_PP_SEQ_SPLIT_180(x) (x) AUTOBOOST_PP_SEQ_SPLIT_179
# define AUTOBOOST_PP_SEQ_SPLIT_181(x) (x) AUTOBOOST_PP_SEQ_SPLIT_180
# define AUTOBOOST_PP_SEQ_SPLIT_182(x) (x) AUTOBOOST_PP_SEQ_SPLIT_181
# define AUTOBOOST_PP_SEQ_SPLIT_183(x) (x) AUTOBOOST_PP_SEQ_SPLIT_182
# define AUTOBOOST_PP_SEQ_SPLIT_184(x) (x) AUTOBOOST_PP_SEQ_SPLIT_183
# define AUTOBOOST_PP_SEQ_SPLIT_185(x) (x) AUTOBOOST_PP_SEQ_SPLIT_184
# define AUTOBOOST_PP_SEQ_SPLIT_186(x) (x) AUTOBOOST_PP_SEQ_SPLIT_185
# define AUTOBOOST_PP_SEQ_SPLIT_187(x) (x) AUTOBOOST_PP_SEQ_SPLIT_186
# define AUTOBOOST_PP_SEQ_SPLIT_188(x) (x) AUTOBOOST_PP_SEQ_SPLIT_187
# define AUTOBOOST_PP_SEQ_SPLIT_189(x) (x) AUTOBOOST_PP_SEQ_SPLIT_188
# define AUTOBOOST_PP_SEQ_SPLIT_190(x) (x) AUTOBOOST_PP_SEQ_SPLIT_189
# define AUTOBOOST_PP_SEQ_SPLIT_191(x) (x) AUTOBOOST_PP_SEQ_SPLIT_190
# define AUTOBOOST_PP_SEQ_SPLIT_192(x) (x) AUTOBOOST_PP_SEQ_SPLIT_191
# define AUTOBOOST_PP_SEQ_SPLIT_193(x) (x) AUTOBOOST_PP_SEQ_SPLIT_192
# define AUTOBOOST_PP_SEQ_SPLIT_194(x) (x) AUTOBOOST_PP_SEQ_SPLIT_193
# define AUTOBOOST_PP_SEQ_SPLIT_195(x) (x) AUTOBOOST_PP_SEQ_SPLIT_194
# define AUTOBOOST_PP_SEQ_SPLIT_196(x) (x) AUTOBOOST_PP_SEQ_SPLIT_195
# define AUTOBOOST_PP_SEQ_SPLIT_197(x) (x) AUTOBOOST_PP_SEQ_SPLIT_196
# define AUTOBOOST_PP_SEQ_SPLIT_198(x) (x) AUTOBOOST_PP_SEQ_SPLIT_197
# define AUTOBOOST_PP_SEQ_SPLIT_199(x) (x) AUTOBOOST_PP_SEQ_SPLIT_198
# define AUTOBOOST_PP_SEQ_SPLIT_200(x) (x) AUTOBOOST_PP_SEQ_SPLIT_199
# define AUTOBOOST_PP_SEQ_SPLIT_201(x) (x) AUTOBOOST_PP_SEQ_SPLIT_200
# define AUTOBOOST_PP_SEQ_SPLIT_202(x) (x) AUTOBOOST_PP_SEQ_SPLIT_201
# define AUTOBOOST_PP_SEQ_SPLIT_203(x) (x) AUTOBOOST_PP_SEQ_SPLIT_202
# define AUTOBOOST_PP_SEQ_SPLIT_204(x) (x) AUTOBOOST_PP_SEQ_SPLIT_203
# define AUTOBOOST_PP_SEQ_SPLIT_205(x) (x) AUTOBOOST_PP_SEQ_SPLIT_204
# define AUTOBOOST_PP_SEQ_SPLIT_206(x) (x) AUTOBOOST_PP_SEQ_SPLIT_205
# define AUTOBOOST_PP_SEQ_SPLIT_207(x) (x) AUTOBOOST_PP_SEQ_SPLIT_206
# define AUTOBOOST_PP_SEQ_SPLIT_208(x) (x) AUTOBOOST_PP_SEQ_SPLIT_207
# define AUTOBOOST_PP_SEQ_SPLIT_209(x) (x) AUTOBOOST_PP_SEQ_SPLIT_208
# define AUTOBOOST_PP_SEQ_SPLIT_210(x) (x) AUTOBOOST_PP_SEQ_SPLIT_209
# define AUTOBOOST_PP_SEQ_SPLIT_211(x) (x) AUTOBOOST_PP_SEQ_SPLIT_210
# define AUTOBOOST_PP_SEQ_SPLIT_212(x) (x) AUTOBOOST_PP_SEQ_SPLIT_211
# define AUTOBOOST_PP_SEQ_SPLIT_213(x) (x) AUTOBOOST_PP_SEQ_SPLIT_212
# define AUTOBOOST_PP_SEQ_SPLIT_214(x) (x) AUTOBOOST_PP_SEQ_SPLIT_213
# define AUTOBOOST_PP_SEQ_SPLIT_215(x) (x) AUTOBOOST_PP_SEQ_SPLIT_214
# define AUTOBOOST_PP_SEQ_SPLIT_216(x) (x) AUTOBOOST_PP_SEQ_SPLIT_215
# define AUTOBOOST_PP_SEQ_SPLIT_217(x) (x) AUTOBOOST_PP_SEQ_SPLIT_216
# define AUTOBOOST_PP_SEQ_SPLIT_218(x) (x) AUTOBOOST_PP_SEQ_SPLIT_217
# define AUTOBOOST_PP_SEQ_SPLIT_219(x) (x) AUTOBOOST_PP_SEQ_SPLIT_218
# define AUTOBOOST_PP_SEQ_SPLIT_220(x) (x) AUTOBOOST_PP_SEQ_SPLIT_219
# define AUTOBOOST_PP_SEQ_SPLIT_221(x) (x) AUTOBOOST_PP_SEQ_SPLIT_220
# define AUTOBOOST_PP_SEQ_SPLIT_222(x) (x) AUTOBOOST_PP_SEQ_SPLIT_221
# define AUTOBOOST_PP_SEQ_SPLIT_223(x) (x) AUTOBOOST_PP_SEQ_SPLIT_222
# define AUTOBOOST_PP_SEQ_SPLIT_224(x) (x) AUTOBOOST_PP_SEQ_SPLIT_223
# define AUTOBOOST_PP_SEQ_SPLIT_225(x) (x) AUTOBOOST_PP_SEQ_SPLIT_224
# define AUTOBOOST_PP_SEQ_SPLIT_226(x) (x) AUTOBOOST_PP_SEQ_SPLIT_225
# define AUTOBOOST_PP_SEQ_SPLIT_227(x) (x) AUTOBOOST_PP_SEQ_SPLIT_226
# define AUTOBOOST_PP_SEQ_SPLIT_228(x) (x) AUTOBOOST_PP_SEQ_SPLIT_227
# define AUTOBOOST_PP_SEQ_SPLIT_229(x) (x) AUTOBOOST_PP_SEQ_SPLIT_228
# define AUTOBOOST_PP_SEQ_SPLIT_230(x) (x) AUTOBOOST_PP_SEQ_SPLIT_229
# define AUTOBOOST_PP_SEQ_SPLIT_231(x) (x) AUTOBOOST_PP_SEQ_SPLIT_230
# define AUTOBOOST_PP_SEQ_SPLIT_232(x) (x) AUTOBOOST_PP_SEQ_SPLIT_231
# define AUTOBOOST_PP_SEQ_SPLIT_233(x) (x) AUTOBOOST_PP_SEQ_SPLIT_232
# define AUTOBOOST_PP_SEQ_SPLIT_234(x) (x) AUTOBOOST_PP_SEQ_SPLIT_233
# define AUTOBOOST_PP_SEQ_SPLIT_235(x) (x) AUTOBOOST_PP_SEQ_SPLIT_234
# define AUTOBOOST_PP_SEQ_SPLIT_236(x) (x) AUTOBOOST_PP_SEQ_SPLIT_235
# define AUTOBOOST_PP_SEQ_SPLIT_237(x) (x) AUTOBOOST_PP_SEQ_SPLIT_236
# define AUTOBOOST_PP_SEQ_SPLIT_238(x) (x) AUTOBOOST_PP_SEQ_SPLIT_237
# define AUTOBOOST_PP_SEQ_SPLIT_239(x) (x) AUTOBOOST_PP_SEQ_SPLIT_238
# define AUTOBOOST_PP_SEQ_SPLIT_240(x) (x) AUTOBOOST_PP_SEQ_SPLIT_239
# define AUTOBOOST_PP_SEQ_SPLIT_241(x) (x) AUTOBOOST_PP_SEQ_SPLIT_240
# define AUTOBOOST_PP_SEQ_SPLIT_242(x) (x) AUTOBOOST_PP_SEQ_SPLIT_241
# define AUTOBOOST_PP_SEQ_SPLIT_243(x) (x) AUTOBOOST_PP_SEQ_SPLIT_242
# define AUTOBOOST_PP_SEQ_SPLIT_244(x) (x) AUTOBOOST_PP_SEQ_SPLIT_243
# define AUTOBOOST_PP_SEQ_SPLIT_245(x) (x) AUTOBOOST_PP_SEQ_SPLIT_244
# define AUTOBOOST_PP_SEQ_SPLIT_246(x) (x) AUTOBOOST_PP_SEQ_SPLIT_245
# define AUTOBOOST_PP_SEQ_SPLIT_247(x) (x) AUTOBOOST_PP_SEQ_SPLIT_246
# define AUTOBOOST_PP_SEQ_SPLIT_248(x) (x) AUTOBOOST_PP_SEQ_SPLIT_247
# define AUTOBOOST_PP_SEQ_SPLIT_249(x) (x) AUTOBOOST_PP_SEQ_SPLIT_248
# define AUTOBOOST_PP_SEQ_SPLIT_250(x) (x) AUTOBOOST_PP_SEQ_SPLIT_249
# define AUTOBOOST_PP_SEQ_SPLIT_251(x) (x) AUTOBOOST_PP_SEQ_SPLIT_250
# define AUTOBOOST_PP_SEQ_SPLIT_252(x) (x) AUTOBOOST_PP_SEQ_SPLIT_251
# define AUTOBOOST_PP_SEQ_SPLIT_253(x) (x) AUTOBOOST_PP_SEQ_SPLIT_252
# define AUTOBOOST_PP_SEQ_SPLIT_254(x) (x) AUTOBOOST_PP_SEQ_SPLIT_253
# define AUTOBOOST_PP_SEQ_SPLIT_255(x) (x) AUTOBOOST_PP_SEQ_SPLIT_254
# define AUTOBOOST_PP_SEQ_SPLIT_256(x) (x) AUTOBOOST_PP_SEQ_SPLIT_255
#
# endif
